# Generated by Django 5.1.4 on 2024-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclues_app', '0002_alter_products_original_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
