# Generated by Django 5.1.4 on 2024-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopclues_app', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products_qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
